openapi: 3.0.0
info:
  title: Address Service API
  version: 1.0.0
  description: API for retrieving random addresses.

servers:
  - url: http://localhost:3001
    description: Development server

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Address:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier for the address.
        address:
          type: string
          description: The address string.

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message describing the issue.

paths:
  /:
    get:
      summary: Health check endpoint
      description: Returns a simple response to indicate the service is running.
      responses:
        '200':
          description: Service is running.
          content:
            text/plain:
              schema:
                type: string
                example: "Address Service"
  
  /address:
    get:
      summary: Retrieve a random address.
      description: |
        Retrieves a random address from the database.
        Requires Basic Authentication.
      security:
        - BasicAuth: []
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '401':
          description: Authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: No address found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api-docs:
    get:
      summary: OpenAPI documentation endpoint
      description: Serves the Swagger UI for the API documentation.
      responses:
        '200':
          description: Swagger UI served successfully.
        '404':
          description: Documentation not found.
